from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import os

def generate_fir_pdf(fir_content: str, case_description: str) -> str:
    
    output_path = "fir_draft.pdf"
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=HexColor('#B8860B'),
        alignment=TA_CENTER,
        spaceAfter=10
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        'Heading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=HexColor('#B8860B'),
        spaceAfter=8,
        spaceBefore=15
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        textColor=HexColor('#333333'),
        spaceAfter=8
    )

    story = []
    
    # Header
    story.append(Paragraph("⚖ NYAY AI", title_style))
    story.append(Paragraph("India's AI Legal Assistant — FIR Draft", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#B8860B')))
    story.append(Spacer(1, 20))
    
    # Case Description
    story.append(Paragraph("CASE DESCRIPTION", heading_style))
    story.append(Paragraph(case_description, body_style))
    story.append(Spacer(1, 10))
    
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor('#cccccc')))
    story.append(Spacer(1, 10))
    
    # FIR Content
    story.append(Paragraph("FIR DRAFT", heading_style))
    
    for line in fir_content.split('\n'):
        if line.strip():
            if line.startswith('**') or line.startswith('#'):
                clean = line.replace('**', '').replace('#', '').strip()
                story.append(Paragraph(clean, heading_style))
            else:
                story.append(Paragraph(line, body_style))
    
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#B8860B')))
    story.append(Spacer(1, 10))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=HexColor('#999999'),
        alignment=TA_CENTER
    )
    story.append(Paragraph(
        "Generated by NYAY AI — This is a draft document. Please consult a lawyer before filing.",
        footer_style
    ))
    
    doc.build(story)
    return output_path